package com.agreemint.pdf;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Currency;
import java.util.List;
import java.util.Locale;

/**
 * Formatting pipes for template placeholders — {@code {{total | currency:"INR"}}}.
 *
 * <p><b>A port, not a design.</b> The canvas has formatted piped variables since
 * the editor shipped ({@code src/lib/variablePipes.ts} in the console) while
 * this renderer's placeholder pattern did not match a pipe at all, so
 * {@code {{total | currency}}} printed literally in plain text and rendered
 * blank in a rich run. Anyone who used the syntax got a document that did not
 * match what they designed — in a product whose entire claim is that those two
 * agree.
 *
 * <p>Every behaviour here is fixed by {@code src/test/resources/pipe-parity.json},
 * which is generated by running the console's own implementation over a table of
 * inputs. This class is asserted against that file rather than against a
 * hand-written expectation, because the failure mode being prevented is
 * <em>almost</em> matching: a thousands separator the canvas omits, a currency
 * symbol placed differently, a rounding mode that differs in the last digit.
 * Regenerate the fixture with
 * {@code npx vitest run src/lib/__pipeFixture.test.ts} in the console whenever
 * the TypeScript changes.
 *
 * <p>Unknown pipe names pass the value through untouched, matching the console.
 * Silently ignoring a typo'd pipe is friendlier than printing an error into
 * somebody's invoice, and the placeholder still resolves.
 */
public final class VariablePipes {

    private VariablePipes() {}

    /** One pipe in a chain: a name and an optional argument. */
    public record Pipe(String name, String arg) {}

    /** A placeholder's key and the pipes applied to it. */
    public record Parsed(String key, List<Pipe> pipes) {}

    private static final String[] MONTHS = {
            "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
    };

    /**
     * Split the inside of {@code {{...}}} into a key and a pipe chain.
     *
     * <p>Mirrors the console's {@code parseVariableExpression}: split on
     * {@code |}, trim, then split each pipe on its FIRST colon so an argument
     * may itself contain one (a date format like {@code "HH:mm"}). Surrounding
     * single or double quotes are stripped from the argument.
     */
    public static Parsed parse(String inner) {
        if (inner == null || inner.isBlank()) return new Parsed("", List.of());
        String[] parts = inner.split("\\|");
        String key = parts[0].trim();
        List<Pipe> pipes = new ArrayList<>();
        for (int i = 1; i < parts.length; i++) {
            String p = parts[i].trim();
            if (p.isEmpty()) continue;
            int colon = p.indexOf(':');
            if (colon < 0) {
                pipes.add(new Pipe(p, null));
                continue;
            }
            String name = p.substring(0, colon).trim();
            String arg = p.substring(colon + 1).trim();
            if (arg.length() >= 2
                    && ((arg.startsWith("\"") && arg.endsWith("\""))
                        || (arg.startsWith("'") && arg.endsWith("'")))) {
                arg = arg.substring(1, arg.length() - 1);
            }
            pipes.add(new Pipe(name, arg));
        }
        return new Parsed(key, pipes);
    }

    /** Apply a chain to an already-stringified value. */
    public static String apply(String value, List<Pipe> pipes) {
        String result = value == null ? "" : value;
        for (Pipe pipe : pipes) {
            result = applyOne(result, pipe.name(), pipe.arg());
        }
        return result;
    }

    private static String applyOne(String str, String name, String arg) {
        boolean empty = str.trim().isEmpty();
        switch (name) {
            case "default":
                return empty ? (arg == null ? "" : arg) : str;
            case "uppercase":
                return str.toUpperCase(Locale.ROOT);
            case "lowercase":
                return str.toLowerCase(Locale.ROOT);
            case "capitalize":
                return capitalize(str);
            case "truncate": {
                int max = parseIntOr(arg, 50);
                // U+2026, the same single character the console appends.
                return str.length() > max ? str.substring(0, max) + "…" : str;
            }
            case "number": {
                Double n = parseDoubleOrNull(str);
                if (n == null) return str;
                int decimals = parseIntOr(arg, 2);
                // `new BigDecimal(double)`, NOT BigDecimal.valueOf.
                //
                // toFixed rounds the actual binary double, and 1.005 is stored
                // as 1.00499999999999989…, so JavaScript yields "1.00".
                // BigDecimal.valueOf goes via Double.toString and sees the
                // shortest decimal that round-trips — "1.005" — which rounds
                // HALF_UP to "1.01". Two plausible answers, one of which does
                // not match the canvas. The exact constructor sees the same
                // bits the browser did.
                //
                // Ties that ARE exactly representable (2.5, 0.125) still round
                // away from zero under HALF_UP, matching toFixed.
                //
                // No grouping separator: toFixed does not emit one.
                return new BigDecimal(n)
                        .setScale(Math.max(0, decimals), RoundingMode.HALF_UP)
                        .toPlainString();
            }
            case "currency": {
                Double n = parseDoubleOrNull(str);
                if (n == null) return str;
                return currency(n, arg == null || arg.isBlank() ? "USD" : arg);
            }
            case "date": {
                if (empty) return "";
                LocalDate d = parseDateOrNull(str);
                if (d == null) return str;
                String fmt = arg == null || arg.isBlank() ? "YYYY-MM-DD" : arg;
                // Ordered exactly as the console chains .replace(): YYYY, then
                // MM, then MMM, then DD. MM before MMM means a literal "MMM"
                // has its first two characters consumed first — reproduced
                // deliberately, because matching the canvas matters more than
                // being right about a format nobody should write.
                return fmt.replace("YYYY", String.valueOf(d.getYear()))
                        .replace("MM", pad2(d.getMonthValue()))
                        .replace("MMM", MONTHS[d.getMonthValue() - 1])
                        .replace("DD", pad2(d.getDayOfMonth()));
            }
            default:
                return str;
        }
    }

    /**
     * {@code Intl.NumberFormat('en-US', {style:'currency', currency: code})}.
     *
     * <p>en-US is hardcoded because the console hardcodes it. That is why INR
     * formats as {@code ₹2,400.00} — symbol first, Western grouping — rather
     * than in the Indian convention, and changing it here alone would break the
     * parity this class exists to hold.
     */
    private static String currency(double n, String code) {
        try {
            NumberFormat f = NumberFormat.getCurrencyInstance(Locale.US);
            Currency c = Currency.getInstance(code.toUpperCase(Locale.ROOT));
            f.setCurrency(c);
            // setCurrency does NOT adjust the fraction digits — the formatter
            // keeps whatever the locale's own currency uses, so JPY came out
            // as ¥2,400.00 where the browser gives ¥2,400. Intl derives the
            // digits from the currency, so we have to as well.
            int digits = c.getDefaultFractionDigits();
            if (digits >= 0) {
                f.setMinimumFractionDigits(digits);
                f.setMaximumFractionDigits(digits);
            }
            return f.format(n);
        } catch (RuntimeException e) {
            // Unknown code — the console falls back to a bare dollar amount.
            return "$" + BigDecimal.valueOf(n).setScale(2, RoundingMode.HALF_UP).toPlainString();
        }
    }

    /** {@code /\b\w/g} → uppercase: the first word character of every run. */
    private static String capitalize(String s) {
        StringBuilder sb = new StringBuilder(s.length());
        boolean atBoundary = true;
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            boolean isWord = Character.isLetterOrDigit(c) || c == '_';
            sb.append(atBoundary && isWord ? Character.toUpperCase(c) : c);
            atBoundary = !isWord;
        }
        return sb.toString();
    }

    private static String pad2(int v) {
        return v < 10 ? "0" + v : String.valueOf(v);
    }

    private static int parseIntOr(String s, int fallback) {
        if (s == null) return fallback;
        try {
            return Integer.parseInt(s.trim());
        } catch (NumberFormatException e) {
            return fallback;
        }
    }

    /** parseFloat semantics: leading number wins, anything else is null. */
    private static Double parseDoubleOrNull(String s) {
        if (s == null || s.isBlank()) return null;
        try {
            double d = Double.parseDouble(s.trim());
            return Double.isFinite(d) ? d : null;
        } catch (NumberFormatException e) {
            return null;
        }
    }

    private static LocalDate parseDateOrNull(String s) {
        try {
            return LocalDate.parse(s.trim());
        } catch (DateTimeParseException e) {
            return null;
        }
    }
}
